
version: 2
jobs:
  build:
    docker:
      - image: danteev/texlive:v1.6.0
    steps:
      - checkout
      - run: latexmk l2kurz
      - run: make ctan
      - run: mkdir build && cp -r README.md l2kurz.pdf .github/_config.yml l2kurz-ctan.tgz build/
      - store_artifacts:
          path: build/
      - run: if [ "$CIRCLE_BRANCH" == "master" ]; then .circleci/deploy-ghpages.sh build/; fi
